name: aprende_a_decirlo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  url_launcher: ^6.0.4
  video_player: ^2.8.6
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/alfabeto/
    - assets/palabra/
    - assets/videos/
    - assets/perfiles/
    - assets/letras/
