name: aprende_a_decirlo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  flutter:
    sdk: flutter
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/alfabeto/
    - assets/palabra/
