name: aprende_a_decirlo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.0
  file_picker: ^8.0.3
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  image: ^4.1.7
  image_picker: ^1.1.0
  url_launcher: ^6.0.4
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/perfiles/
    - assets/alfabeto/
    - assets/palabra/
    - assets/videos/
