// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz6qAh9LtJnm0MPxyMelchmDGfah1bdaI',
    appId: '1:1075260168097:web:5b73e5294d320be4ebdde0',
    messagingSenderId: '1075260168097',
    projectId: 'dilo-en-senas',
    authDomain: 'dilo-en-senas.firebaseapp.com',
    storageBucket: 'dilo-en-senas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFunY7BLYflIieAOv9-nbvq6Qy44pstY',
    appId: '1:1075260168097:android:90e0944e1d811af1ebdde0',
    messagingSenderId: '1075260168097',
    projectId: 'dilo-en-senas',
    storageBucket: 'dilo-en-senas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2FiZN2l1SU60wg9M2JdDlRHkmLHQ6jQ',
    appId: '1:1075260168097:ios:8169271a4bd03453ebdde0',
    messagingSenderId: '1075260168097',
    projectId: 'dilo-en-senas',
    storageBucket: 'dilo-en-senas.appspot.com',
    iosBundleId: 'com.aprendeadecirlo.aprendeADecirlo',
  );
}
